"""HTTP client for x402-protected resources — official SDK first (official-first).

Only official components are used:
- header names and codecs: x402.http.constants / x402.http.utils
- payment signing: ExactEvmScheme (EIP-3009 typed data) + EthAccountSigner
- payment models: x402.schemas (PaymentRequired / PaymentRequirements /
  PaymentPayload)

Flow: request -> 402 + PAYMENT-REQUIRED -> budget check -> build and sign the
payload -> retry with PAYMENT-SIGNATURE -> resource body / verificationResult.

Both GET (plain paid resources) and POST (resources addressed with a JSON body)
are supported: the body is always forwarded verbatim, on the first request and
on the retry alike.

The higher-level official paths (hooks, policies, spend controls,
x402HTTPClient / PaymentRoundTripper automatic 402 handling, the official
x402.mcp integration) are described in README.md.
"""

from __future__ import annotations

from typing import Any

import httpx
from x402.http.constants import (
    PAYMENT_REQUIRED_HEADER,
    PAYMENT_SIGNATURE_HEADER,
)
from x402.http.utils import (
    decode_payment_required_header,
    encode_payment_signature_header,
)
from x402.mechanisms.evm.exact.client import ExactEvmScheme
from x402.mechanisms.evm.signer import ClientEvmSigner
from x402.schemas import PaymentPayload, PaymentRequired, PaymentRequirements


class PaidResourceClient:
    """Minimal paid-resource client assembled from official SDK components.

    Everything protocol-related is delegated to the official utils and scheme:
    402 challenge parsing and payment payload encoding included. What is left
    to decide is business policy only: which offer to accept, budget limits,
    key management.
    """

    def __init__(
        self,
        signer: ClientEvmSigner,
        *,
        timeout: float = 10.0,
    ) -> None:
        self._scheme = ExactEvmScheme(signer)
        self._http = httpx.Client(timeout=timeout)

    def fetch(
        self,
        resource_url: str,
        max_amount_wei: int,
        *,
        method: str = "GET",
        json_body: dict[str, Any] | None = None,
        extra_headers: dict[str, str] | None = None,
    ) -> str:
        """Fetch an x402-protected resource; refuse to pay above max_amount_wei.

        The JSON body, when given, is sent unchanged with both requests.
        """
        headers = dict(extra_headers or {})
        response = self._request(resource_url, method=method, body=json_body, headers=headers)

        # Not 402: return the body or raise.
        if response.status_code != 402:
            response.raise_for_status()
            return response.text

        # 402: parse the payment requirements with the official utils.
        decoded = decode_payment_required_header(response.headers[PAYMENT_REQUIRED_HEADER])
        if not isinstance(decoded, PaymentRequired):
            # The official decoder also accepts x402 v1 challenges; this bridge
            # quotes and signs v2 only.
            raise ValueError("unsupported x402 version in PAYMENT-REQUIRED header (v2 required)")
        requirements = self._select_requirements(decoded.accepts)
        if int(requirements.amount) > max_amount_wei:
            raise ValueError(f"price {requirements.amount} exceeds max {max_amount_wei}")

        # The official scheme builds and signs the payload (EIP-3009, nonce
        # generated by the official SDK).
        inner = self._scheme.create_payment_payload(requirements)
        payload = PaymentPayload(payload=inner, accepted=requirements)
        headers[PAYMENT_SIGNATURE_HEADER] = encode_payment_signature_header(payload)
        final = self._request(resource_url, method=method, body=json_body, headers=headers)
        final.raise_for_status()
        return final.text

    def _request(
        self,
        resource_url: str,
        *,
        method: str,
        body: dict[str, Any] | None,
        headers: dict[str, str],
    ) -> httpx.Response:
        return self._http.request(method, resource_url, json=body, headers=headers)

    def _select_requirements(self, accepts: list[PaymentRequirements]) -> PaymentRequirements:
        # accepts may offer several payment options (different networks,
        # schemes or amounts). This minimal client takes the first one; a
        # production policy would filter by supported scheme/network and by
        # price before choosing here.
        return accepts[0]
